version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: bigdata_lab1
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/data
      - ./script:/docker-entrypoint-initdb.d
    restart: unless-stopped